classdef (Sealed) FxmlView < handle & matlab.mixin.SetGet
% A completely customizable view that is defined by FXML.

    properties (Dependent)
        autoReload
        source
    end

    methods

        function result = get.autoReload(this)
            % Gets the auto-reload state
            result = hebi_charts_native('hebi_charts_FxmlView_isAutoReload', this.ptr);
        end

        function set.autoReload(this, enableAutoReload)
            % Sets the auto-reload state
            %
            %   Inputs:
            %       enableAutoReload
            hebi_charts_native('hebi_charts_FxmlView_setAutoReload', this.ptr, enableAutoReload);
        end

        function result = get.source(this)
            % Gets the FXML source location
            result = hebi_charts_native('hebi_charts_FxmlView_getSource', this.ptr);
        end

        function set.source(this, pathOrUrl)
            % Sets the file path or web-url to a .fxml file
            %
            %   Inputs:
            %       pathOrUrl - path or url to an FXML file
            %
            %   Throws:
            %       Error on internal errors
            hebi_charts_native('hebi_charts_FxmlView_setSource', this.ptr, pathOrUrl);
            if status_ ~= 0
                error(['Encountered error in FxmlView.set.source' ': ' hebi_charts_native('hebi_charts_Runtime_getLastErrorString')]);
            end
        end

        function obj = addLineChart(this, fxId, varargin)
            % Creates a 2d line chart with the given size
            %
            %   Inputs:
            %       fxId
            %
            %   Throws:
            %       Error on internal errors
            ptr_ = hebi_charts_native('hebi_charts_FxmlView_addLineChart', this.ptr, fxId);
            if isempty(ptr_)
                error(['Failed to create hebi_charts.LineChart in FxmlView.addLineChart' ': ' hebi_charts_native('hebi_charts_Runtime_getLastErrorString')]);
            end
            obj = hebi_charts.LineChart(ptr_, varargin{:});
        end

        function obj = addScope(this, fxId, varargin)
            % Creates a line chart with a pre-set time axis in [s]
            %
            %   Inputs:
            %       fxId
            %
            %   Throws:
            %       Error on internal errors
            ptr_ = hebi_charts_native('hebi_charts_FxmlView_addScope', this.ptr, fxId);
            if isempty(ptr_)
                error(['Failed to create hebi_charts.LineChart in FxmlView.addScope' ': ' hebi_charts_native('hebi_charts_Runtime_getLastErrorString')]);
            end
            obj = hebi_charts.LineChart(ptr_, varargin{:});
        end

        function obj = addPercentileHistogram(this, fxId, varargin)
            % Creates a percentile histogram with the given size
            %
            %   Inputs:
            %       fxId
            %
            %   Throws:
            %       Error on internal errors
            ptr_ = hebi_charts_native('hebi_charts_FxmlView_addPercentileHistogram', this.ptr, fxId);
            if isempty(ptr_)
                error(['Failed to create hebi_charts.HistogramChart in FxmlView.addPercentileHistogram' ': ' hebi_charts_native('hebi_charts_Runtime_getLastErrorString')]);
            end
            obj = hebi_charts.HistogramChart(ptr_, varargin{:});
        end

        function obj = addLatencyChart(this, fxId, varargin)
            % Utility for creating a percentile histogram for measuring latency in [s]
            %
            %   Inputs:
            %       fxId
            %
            %   Throws:
            %       Error on internal errors
            ptr_ = hebi_charts_native('hebi_charts_FxmlView_addLatencyChart', this.ptr, fxId);
            if isempty(ptr_)
                error(['Failed to create hebi_charts.HistogramChart in FxmlView.addLatencyChart' ': ' hebi_charts_native('hebi_charts_Runtime_getLastErrorString')]);
            end
            obj = hebi_charts.HistogramChart(ptr_, varargin{:});
        end

        function obj = addScene3d(this, fxId, varargin)
            % Creates a 3d chart with the given size
            %
            %   Inputs:
            %       fxId
            %
            %   Throws:
            %       Error on internal errors
            ptr_ = hebi_charts_native('hebi_charts_FxmlView_addScene3d', this.ptr, fxId);
            if isempty(ptr_)
                error(['Failed to create hebi_charts.Scene3d in FxmlView.addScene3d' ': ' hebi_charts_native('hebi_charts_Runtime_getLastErrorString')]);
            end
            obj = hebi_charts.Scene3d(ptr_, varargin{:});
        end

        function obj = addStreamView(this, file, fxId)
            % Shows a shared-memory stream generated by hebi-video tools
            %
            %   Inputs:
            %       file
            %       fxId
            %
            %   Throws:
            %       Error on internal errors
            ptr_ = hebi_charts_native('hebi_charts_FxmlView_addStreamView', this.ptr, file, fxId);
            if isempty(ptr_)
                error(['Failed to create hebi_charts.StreamView in FxmlView.addStreamView' ': ' hebi_charts_native('hebi_charts_Runtime_getLastErrorString')]);
            end
            obj = hebi_charts.StreamView(ptr_);
        end

        function obj = addFxmlView(this, fxId, varargin)
            % Shows a panel for interactive controls
            %
            %   Inputs:
            %       fxId
            %
            %   Throws:
            %       Error on internal errors
            ptr_ = hebi_charts_native('hebi_charts_FxmlView_addFxmlView', this.ptr, fxId);
            if isempty(ptr_)
                error(['Failed to create hebi_charts.FxmlView in FxmlView.addFxmlView' ': ' hebi_charts_native('hebi_charts_Runtime_getLastErrorString')]);
            end
            obj = hebi_charts.FxmlView(ptr_, varargin{:});
        end

    end

    methods(Access = public, Hidden = true)
        function this = FxmlView(ptr, varargin)
            if ~isnumeric(ptr) && ~isa(ptr, 'lib.pointer')
                error('FxmlView constructor expects a C pointer type');
            end
            this.ptr = ptr;

            % Apply name-value pairs to properties, if provided
            if numel(varargin) > 1
                this.set(varargin{:});
            end
        end
    end
    properties (SetAccess = private, GetAccess = private, Hidden = true)
        ptr = [];
    end

    methods(Access = public, Hidden = true)

        function ptr = c_ptr(this)
            ptr = this.ptr;
        end

        function delete(this) % destructor
             if ~isempty(this.ptr)
                hebi_charts_native('hebi_charts_FxmlView_release', this.ptr);
                this.ptr = [];
            end
        end

        % Inherited handle methods that should be omitted from auto - complete
        function varargout = addlistener(varargin)
            varargout{:} = addlistener@handle(varargin{:});
        end
        function varargout = eq(varargin)
            varargout{:} = eq@handle(varargin{:});
        end
        function varargout = findobj(varargin)
            varargout{:} = findobj@handle(varargin{:});
        end
        function varargout = findprop(varargin)
            varargout{:} = findprop@handle(varargin{:});
        end
        function varargout = ge(varargin)
            varargout{:} = ge@handle(varargin{:});
        end
        function varargout = gt(varargin)
            varargout{:} = gt@handle(varargin{:});
        end
        function varargout = le(varargin)
            varargout{:} = le@handle(varargin{:});
        end
        function varargout = listener(varargin)
            varargout{:} = listener@handle(varargin{:});
        end
        function varargout = lt(varargin)
            varargout{:} = lt@handle(varargin{:});
        end
        function varargout = ne(varargin)
            varargout{:} = ne@handle(varargin{:});
        end
        function varargout = notify(varargin)
            varargout{:} = notify@handle(varargin{:});
        end

    end

end